name: Security Scan and Issue Creation

on:
  push:
    branches:
      - main

permissions:
  actions: write
  issues: write  # Grants permission to create issues
  security-events: write

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code test
          args: "--sarif-file-output=path/snyk.sarif"

      - name: Check SARIF file and Upload Results
        run: |
          ls -la
          cat path/snyk.sarif

      - name: Upload SARIF Report to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: path/snyk.sarif
          token: ${{ secrets.GITHUB_TOKEN }}
          wait-for-processing: true

      - name: Parse SARIF and Create Issue if Vulnerabilities Found
        id: issue-creation
        run: |
          if [ -f path/snyk.sarif ]; then
            # Extract vulnerabilities from the SARIF report
            VULNERABILITIES=$(jq '.runs[].results[] | select(.ruleId=="snyk")' path/snyk.sarif)
            
            if [ -n "$VULNERABILITIES" ]; then
              echo "Vulnerabilities found! Creating an issue..."
              ISSUE_TITLE="Security Alert: Vulnerabilities Found in Code"
              ISSUE_BODY="Snyk has detected vulnerabilities in the code. Please review the following:\n\n$VULNERABILITIES"

              # Create an issue using GitHub API
              curl -X POST -H "Authorization: token ${{ secrets.GH_PAT }}" \
                -d "{\"title\":\"$ISSUE_TITLE\", \"body\":\"$ISSUE_BODY\", \"labels\":[\"security\"]}" \
                https://api.github.com/repos/${{ github.repository }}/issues
            else
              echo "No vulnerabilities found."
            fi
          else
            echo "SARIF file not found."
          fi
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
