name: Code Issue Detection and GitHub Issue Creation

on:
  push:
    branches:
      - main

permissions:
  issues: write  # Grant permission to create issues

jobs:
  code-issues:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install flake8

      - name: Run flake8 to detect issues
        run: |
          flake8 . --format=json > flake8-report.json || true

      - name: Check if flake8 report exists and create issues
        run: |
          if [ -f "flake8-report.json" ]; then
            # Extract issues from flake8 JSON output
            issues=$(cat flake8-report.json | jq -r '.[] | "\(.message) - Line: \(.line) Column: \(.column)"')
            
            # If no issues found, exit early
            if [ -z "$issues" ]; then
              echo "No issues found by flake8"
              exit 0
            fi

            # Iterate through the issues and create GitHub issues
            for issue in $issues; do
              echo "Creating issue: $issue"
              curl -X POST \
                -H "Authorization: token ${{ secrets.GH_PAT }}" \  # Use your GitHub Personal Access Token here
                -d "{\"title\": \"Code Issue: $issue\", \"body\": \"Description: This issue was detected by flake8. Please review.\", \"labels\": [\"code\", \"linting\"]}" \
                "https://api.github.com/repos/${{ github.repository }}/issues" \
                -w "\nResponse code: %{http_code}\n"
            done
          fi
