name: Snyk Security Scan with SARIF Upload and Issue Creation 
on:
  push:
    branches:
      - main

permissions:
  actions: write
  issues: write  # Grant permission to create issues
  security-events: write

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master
        continue-on-error: true
        env: 
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code test
          args: "--sarif-file-output=path/snyk.sarif --json-file-output=path/snyk_results.json"

      - name: Check if SARIF file exists and print contents
        run: |
          ls -la  # List files to check if snyk.sarif exists
          cat path/snyk.sarif  # Display the contents of the SARIF file

      - name: Upload SARIF report to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: path/snyk.sarif
          token: ${{ secrets.GITHUB_TOKEN }}
          wait-for-processing: true

      - name: Check for vulnerabilities and create an issue
        id: snyk-issue
        run: |
          # Unset GITHUB_TOKEN to avoid conflicts with GH_PAT
          unset GITHUB_TOKEN

          # Check if snyk_results.json exists and process it
          if [ -f path/snyk_results.json ]; then
            VULNERABILITIES=$(jq '.vulnerabilities' path/snyk_results.json)
            if [ "$VULNERABILITIES" != "[]" ]; then
              echo "Vulnerabilities found! Creating an issue..."

              ISSUE_TITLE="Snyk Alert: Credentials in Code Detected"
              ISSUE_BODY="Snyk has detected credentials in the code. Please review the following vulnerabilities:\n\n$VULNERABILITIES"

              # Create the issue using the GH_PAT directly without 'gh auth login'
              curl -X POST -H "Authorization: token ${{ secrets.GH_PAT }}" \
                -d "{\"title\":\"$ISSUE_TITLE\", \"body\":\"$ISSUE_BODY\", \"labels\":[\"security\"]}" \
                https://api.github.com/repos/${{ github.repository }}/issues
            else
              echo "No vulnerabilities found."
            fi
          else
            echo "Snyk results file not found."
          fi
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
