name: Snyk Security Scan with SARIF Upload and Issue Creation

on:
  push:
    branches:
      - main

permissions:
  actions: write
  issues: write  # Grant permission to create issues
  security-events: write

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master
        continue-on-error: true
        env: 
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code test
          args: "--sarif-file-output=snyk.sarif"  # Ensure the file is saved in the correct location

      - name: Check if SARIF file exists and print contents
        run: |
          ls -la  # List files to check if snyk.sarif exists
          cat snyk.sarif  # Display the contents of the SARIF file

      - name: Upload SARIF report to GitHub
        id: upload-sarif
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif
          token: ${{ secrets.GITHUB_TOKEN }}
          wait-for-processing: true

      - name: Create GitHub Issue
        run: |
          # Define the issue title and body
          issue_title="Security Issue: Sample Issue"
          issue_body="Description: This is a sample security issue detected in the repository. Please review the code for vulnerabilities."

          # Use curl to create a GitHub issue, making sure JSON is correctly escaped and quoted
          curl -X POST \
            -H "Authorization: token ${{ secrets.GH_PAT }}" \
            -d "{\"title\": \"${issue_title}\", \"body\": \"${issue_body}\", \"labels\": [\"security\", \"vulnerability\"]}" \
            "https://api.github.com/repos/${{ github.repository }}/issues"
