name: Snyk Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  snyk:
    name: Run Snyk Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Node.js (for Snyk)
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Make sure you're using the correct version
      
      - name: Install Snyk
        run: npm install -g snyk
      
      - name: Run Snyk test
        run: snyk code test --sarif > snyk-code.sarif
        continue-on-error: true  # Prevents the job from failing if vulnerabilities are found
      
      - name: Upload SARIF report to GitHub
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk-code.sarif
