# Check if the response is a valid array of alerts
if echo "$RESPONSE" | jq -e 'type == "array"' > /dev/null; then
  ALERT_COUNT=$(echo "$RESPONSE" | jq '. | length')
  echo "Total Alerts: $ALERT_COUNT"

  if [ "$ALERT_COUNT" -gt 0 ]; then
    echo "Code Scanning Alerts found! Creating issues..."

    echo "$RESPONSE" | jq -r '.[] | 
      {
        rule_name: .rule.name,
        message: .message.text,
        severity: .severity,
        alert_url: .html_url,
        location: .locations[0].physicalLocation.artifactLocation.uri,
        start_line: .locations[0].physicalLocation.region.startLine
      }' | while read alert; do

      RULE_NAME=$(echo $alert | jq -r '.rule_name')
      MESSAGE=$(echo $alert | jq -r '.message')
      SEVERITY=$(echo $alert | jq -r '.severity')
      ALERT_URL=$(echo $alert | jq -r '.alert_url')
      LOCATION=$(echo $alert | jq -r '.location')
      START_LINE=$(echo $alert | jq -r '.start_line')

      ISSUE_TITLE="Fix code scanning alert - $RULE_NAME"
      ISSUE_BODY="<!-- Warning: The suggested title contains the alert rule name. This can expose security information. -->\n\n
      **Severity**: $SEVERITY\n
      **Message**: $MESSAGE\n
      **Location**: $LOCATION\n
      **Start Line**: $START_LINE\n\n
      Tracking issue for:\n- [ ] $ALERT_URL"
      
      curl -X POST -H "Authorization: token ${{ secrets.GH_PAT }}" \
        -d "{\"title\":\"$ISSUE_TITLE\", \"body\":\"$ISSUE_BODY\", \"labels\":[\"security\"]}" \
        https://api.github.com/repos/${{ github.repository }}/issues
    done
  else
    echo "No code scanning alerts found."
  fi
else
  echo "Error: The response is not a valid array of alerts."
  exit 1
fi
