name: Snyk Security Scan with SARIF Upload and Issue Creation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  snyk_security_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Snyk CLI
        run: |
          curl -sL https://github.com/snyk/snyk/releases/download/v1.1041.0/snyk-linux-amd64 -o /usr/local/bin/snyk
          chmod +x /usr/local/bin/snyk

      - name: Authenticate Snyk CLI
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk Security Scan
        id: snyk_scan
        run: |
          snyk test --all-projects --json > snyk-report.json
          snyk monitor --all-projects

      - name: Upload SARIF Results to GitHub
        if: ${{ always() }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-report.json  # SARIF file output from Snyk

      - name: Check for Vulnerabilities and Create Issue
        if: ${{ steps.snyk_scan.outcome == 'failure' }}
        run: |
          echo "Vulnerabilities found, creating an issue"
          curl -X POST https://api.github.com/repos/${{ github.repository }}/issues \
            -H "Authorization: Bearer ${{ secrets.GH_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d @- <<EOF
            {
              "title": "Security vulnerabilities found in the code",
              "body": "Snyk security scan has found vulnerabilities in the code. Please check the Snyk scan report for details.",
              "labels": ["security", "bug"]
            }
            EOF
