name: Create Issue from SARIF

on:
  push:
    branches:
      - main

jobs:
  create-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Dummy SARIF File
        run: |
          echo '{
            "runs": [
              {
                "results": [
                  {
                    "message": {
                      "text": "Sample Issue"
                    },
                    "locations": [
                      {
                        "physicalLocation": {
                          "artifactLocation": {
                            "uri": "file:///sample/path"
                          }
                        }
                      }
                    ]
                  }
                ]
              }
            ]
          }' > snyk.sarif

      - name: Extract Issues from SARIF and Create GitHub Issues
        run: |
          issues=$(cat snyk.sarif | jq -r '.runs[0].results[] | "\(.message.text) - URI: \(.locations[0].physicalLocation.artifactLocation.uri)"')
          echo "Extracted Issues: $issues"
          if [ -z "$issues" ]; then
            echo "No issues found in SARIF report"
            exit 0
          fi

          # Create issues
          for issue in $issues; do
            echo "Creating issue: $issue"
            curl -X POST \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -d "{\"title\": \"Security Issue: $issue\", \"body\": \"Description: This issue was detected by SARIF scan. Please review.\", \"labels\": [\"security\", \"vulnerability\"]}" \
              https://api.github.com/repos/${{ github.repository }}/issues \
              -w "\nResponse code: %{http_code}\n"
          done
