name: Code Issue Detection and GitHub Issue Creation

on:
  push:
    branches:
      - main

permissions:
  issues: write  # Grant permission to create issues

jobs:
  code-issues:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm install eslint

      - name: Run ESLint to detect issues
        run: |
          npx eslint . --format=json > eslint-report.json || true

      - name: Check if ESLint report exists and create issues
        run: |
          if [ -f "eslint-report.json" ]; then
            # Extract issues from ESLint JSON output
            issues=$(cat eslint-report.json | jq -r '.[] | .messages[] | "\(.message) - \(.ruleId) - Line: \(.line) Column: \(.column)"')
            
            # If no issues found, exit early
            if [ -z "$issues" ]; then
              echo "No issues found by ESLint"
              exit 0
            fi

            # Iterate through the issues and create GitHub issues
            for issue in $issues; do
              echo "Creating issue: $issue"
              curl -X POST \
                -H "Authorization: token ${{ secrets.GH_PAT }}" \  # Use your GitHub Personal Access Token here
                -d "{\"title\": \"Code Issue: $issue\", \"body\": \"Description: This issue was detected by ESLint. Please review.\", \"labels\": [\"code\", \"linting\"]}" \
                "https://api.github.com/repos/${{ github.repository }}/issues" \
                -w "\nResponse code: %{http_code}\n"
            done
          fi
